### ISSUE TITLE
`check-unapplied-migrations` doesn't fail when there is model changes without migrations.

### ISSUE THREAD

**Issue by sh-cho** [ecugol/pre-commit-hooks-django#3]
```bash
# check1.sh
if python manage.py migrate --check ; then
  echo "succeeded"
else
  echo "failed"
fi
```

I just made simple script if command returns 0 or non-zero.

![image](https://user-images.githubusercontent.com/11611397/132558723-8fc400d3-b4c2-49d6-9171-3d800d2bf874.png)

If migration has not been made, `python manage.py migrate --check` doesn't fail even though there would be some warning messages.

But `makemigrations --check` returns non-zero when there is model changes without migrations.

> ### makemigrations --check
> 
> Makes makemigrations exit with a non-zero status when model changes without migrations are detected.
> (https://docs.djangoproject.com/en/3.2/ref/django-admin/#cmdoption-makemigrations-check)

```bash
# check2.sh
if python manage.py makemigrations --check --dry-run ; then
  echo "succeeded"
else
  echo "failed"
fi
```

![image](https://user-images.githubusercontent.com/11611397/132560124-a8c4a7bc-0db2-4b6c-9114-305972fd8f02.png)

It exits with non-zero (even though there are no warnings)

So how about merge `check-unapplied-migrations` and `check-absent-migrations`? Because it's error-prone.

**Comment by ecugol** [comment]
@sh-cho Hello. I think it's better to keep each hook to do one job only. `check-unapplied-migrations` was added because we had situations when developers don't migrate new DB changes and then commit the untested migrations to repository. 

So, if you need to check for not applied, but created migrations together with checking for migrations which wasn't created for models changes, just use both hooks.
